import type { ReactNode } from "react";
import { Header } from "./header/Header";
import styles from "../../styles/Home.module.css";
import Head from "next/head";

type LayoutProps = {
  readonly children: ReactNode;
  mainStyle?: string;
};

export const Layout = ({ children, mainStyle }: LayoutProps) => (
  <div className={styles.main}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <meta
        name="viewport"
        content="width=device-width, height=device-height, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"
      />
      <link rel="icon" href="/logo.svg" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="anonymous"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
        rel="stylesheet"
      />
    </Head>
    <Header />
    <main className={mainStyle ? mainStyle : styles.container}>{children}</main>
  </div>
);
