import type { ReactNode } from "react";
import { Header } from "./header/Header";
import styles from "../../styles/Home.module.css";
import Head from "next/head";

type LayoutProps = {
  readonly children: ReactNode;
};

export const Layout = ({ children }: LayoutProps) => (
  <div className={styles.main}>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.svg" />
    </Head>
    <Header />
    <main className={styles.container}>{children}</main>
  </div>
);
